// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication27.Models
{
    public partial class Odbici
    {
        public int OdbiciId { get; set; }
        public int RadniciId { get; set; }
        public string Naziv { get; set; }
        public decimal Iznos { get; set; }

        public virtual Radnici Radnici { get; set; }
    }
}