// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace WebApplication27.Models
{
    public partial class ZAPOSLENI_Firma03Context : DbContext
    {
        public ZAPOSLENI_Firma03Context()
        {
        }

        public ZAPOSLENI_Firma03Context(DbContextOptions<ZAPOSLENI_Firma03Context> options)
            : base(options)
        {
        }

        public virtual DbSet<Bonus> Bonus { get; set; }
        public virtual DbSet<Odbici> Odbici { get; set; }
        public virtual DbSet<Odmor> Odmor { get; set; }
        public virtual DbSet<Plata> Plata { get; set; }
        public virtual DbSet<Pozicija> Pozicija { get; set; }
        public virtual DbSet<Radnici> Radnici { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Bonus>(entity =>
            {
                entity.Property(e => e.Iznos).HasColumnType("decimal(10, 2)");

                entity.Property(e => e.Naziv)
                    .IsRequired()
                    .HasMaxLength(48)
                    .IsUnicode(false);

                entity.HasOne(d => d.Radnici)
                    .WithMany(p => p.Bonus)
                    .HasForeignKey(d => d.RadniciId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Bonus__RadniciId__412EB0B6");
            });

            modelBuilder.Entity<Odbici>(entity =>
            {
                entity.Property(e => e.Iznos).HasColumnType("decimal(10, 2)");

                entity.Property(e => e.Naziv)
                    .IsRequired()
                    .HasMaxLength(48)
                    .IsUnicode(false);

                entity.HasOne(d => d.Radnici)
                    .WithMany(p => p.Odbici)
                    .HasForeignKey(d => d.RadniciId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Odbici__RadniciI__440B1D61");
            });

            modelBuilder.Entity<Odmor>(entity =>
            {
                entity.Property(e => e.Naziv)
                    .HasMaxLength(48)
                    .IsUnicode(false);

                entity.HasOne(d => d.Radnici)
                    .WithMany(p => p.Odmor)
                    .HasForeignKey(d => d.RadniciId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Odmor__RadniciId__46E78A0C");
            });

            modelBuilder.Entity<Plata>(entity =>
            {
                entity.Property(e => e.DatumPromjene)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Iznos).HasColumnType("decimal(10, 2)");

                entity.HasOne(d => d.Radnici)
                    .WithMany(p => p.Plata)
                    .HasForeignKey(d => d.RadniciId)
                    .HasConstraintName("FK__Plata__RadniciId__3D5E1FD2");
            });

            modelBuilder.Entity<Pozicija>(entity =>
            {
                entity.Property(e => e.Naziv)
                    .IsRequired()
                    .HasMaxLength(36)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Radnici>(entity =>
            {
                entity.Property(e => e.DatumZaposlenja)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Ime)
                    .IsRequired()
                    .HasMaxLength(48)
                    .IsUnicode(false);

                entity.Property(e => e.PeriodPozicija).HasColumnType("date");

                entity.Property(e => e.Prezime)
                    .IsRequired()
                    .HasMaxLength(48)
                    .IsUnicode(false);

                entity.HasOne(d => d.Nadredjeni)
                    .WithMany(p => p.InverseNadredjeni)
                    .HasForeignKey(d => d.NadredjeniId)
                    .HasConstraintName("FK__Radnici__Nadredj__398D8EEE");

                entity.HasOne(d => d.Pozicija)
                    .WithMany(p => p.Radnici)
                    .HasForeignKey(d => d.PozicijaId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Radnici__Pozicij__38996AB5");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}